-- Table: via-car-message
-- This table stores the conversation history for each user.

CREATE TABLE public."via-car-message" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  message_text TEXT NOT NULL,
  assistant_response TEXT,
  input_tokens INT DEFAULT 0,
  output_tokens INT DEFAULT 0,
  sent_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  
  CONSTRAINT "via-car-message_pkey" PRIMARY KEY (id),
  CONSTRAINT "via-car-message_user_id_fkey" FOREIGN KEY (user_id) 
    REFERENCES public."via-car-user" (user_id) 
    ON DELETE CASCADE -- Optional: Deletes messages if the user is deleted
);

-- Create an index on user_id and sent_at for faster queries
CREATE INDEX "idx_via-car-message_user_id_sent_at" 
  ON public."via-car-message" (user_id, sent_at DESC);

-- Add comments for clarity
COMMENT ON TABLE public."via-car-message" IS 'Stores messages sent by users and responses from the assistant.';
COMMENT ON COLUMN public."via-car-message".user_id IS 'Foreign key referencing the user in the via-car-user table.';